'use client';

import { useState } from 'react';
import type { WalletAnalysis } from '@/types';

interface ExportButtonProps {
  analysis: WalletAnalysis;
  narrative: string | null;
  sarDraft: string | null;
}

const SIGNAL_LABELS: Record<string, string> = {
  ofac_match: 'OFAC MATCH',
  mixer_interaction: 'MIXER INTERACTION',
  rapid_fund_movement: 'RAPID FUND MOVEMENT',
  high_risk_counterparty: 'HIGH-RISK COUNTERPARTY',
  volume_anomaly: 'VOLUME ANOMALY',
  community_red_flags: 'COMMUNITY RED FLAGS',
};

function buildReport(analysis: WalletAnalysis, narrative: string | null, sarDraft: string | null): string {
  const hr = '─'.repeat(72);
  const date = new Date(analysis.analyzedAt).toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'short' });
  const caseId = `CLR-${new Date().toISOString().split('T')[0]}-${analysis.address.slice(2, 8).toUpperCase()}`;

  const signalRows = Object.values(analysis.riskScore.signals)
    .sort((a, b) => {
      if (a.triggered && !b.triggered) return -1;
      if (!a.triggered && b.triggered) return 1;
      return b.weight - a.weight;
    })
    .map(s => {
      const label = (SIGNAL_LABELS[s.name] ?? s.name.replace(/_/g, ' ').toUpperCase()).padEnd(30);
      const score = s.triggered ? `+${s.score}`.padStart(4) : '   0';
      const detail = s.detail ? `  // ${s.detail}` : '';
      return `  ${s.triggered ? '●' : '○'}  ${label}  ${score} / ${s.weight}${detail}`;
    })
    .join('\n');

  const typologyRows = analysis.typologies
    .filter(t => t.triggered)
    .sort((a, b) => b.confidence - a.confidence)
    .map(t => {
      const pct = `${Math.round(t.confidence * 100)}%`;
      return `  ● ${t.name.toUpperCase()} (${pct} confidence)\n    ${t.fatfReference}\n    ${t.rationale}`;
    })
    .join('\n\n');

  const ofacLine = analysis.ofacResult.matched
    ? `OFAC SDN MATCH — ${analysis.ofacResult.matchedEntity ?? 'Sanctioned Entity'}`
    : 'OFAC SDN: CLEAR';

  return [
    'CLEARCHAIN — WALLET ANALYSIS REPORT',
    'AI-ASSISTED DRAFT — NOT A FILED SAR — FOR COMPLIANCE REVIEW ONLY',
    hr,
    `Case ID:     ${caseId}`,
    `Address:     ${analysis.address}`,
    `Analyzed:    ${date}`,
    `Network:     Ethereum Mainnet`,
    `OFAC:        ${ofacLine}`,
    hr,
    '',
    'RISK ASSESSMENT',
    hr,
    `Risk Score:  ${analysis.riskScore.total} / 100  [${analysis.riskScore.level} RISK]`,
    `Signals:     ${Object.values(analysis.riskScore.signals).filter(s => s.triggered).length} of ${Object.values(analysis.riskScore.signals).length} triggered`,
    '',
    'SIGNAL BREAKDOWN',
    signalRows,
    '',
    hr,
    '',
    'AML TYPOLOGIES',
    typologyRows || '  No typologies matched.',
    '',
    hr,
    '',
    'AI NARRATIVE',
    (narrative && !narrative.toLowerCase().includes('generation failed'))
      ? narrative
      : '(Narrative generation failed or unavailable.)',
    '',
    hr,
    '',
    'SAR DRAFT',
    'FOR COMPLIANCE OFFICER REVIEW ONLY — NOT A FILED SAR',
    '',
    (sarDraft && !sarDraft.toLowerCase().includes('generation failed'))
      ? sarDraft
      : '(SAR draft generation failed or unavailable.)',
    '',
    hr,
    `Generated by ClearChain  ·  ${new Date().toISOString()}`,
  ].join('\n');
}

export default function ExportButton({ analysis, narrative, sarDraft }: ExportButtonProps) {
  const [exporting, setExporting] = useState(false);
  const [hovered, setHovered] = useState(false);

  function handleExport() {
    setExporting(true);
    try {
      const text = buildReport(analysis, narrative, sarDraft);
      const blob = new Blob([text], { type: 'text/plain; charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `clearchain-${analysis.address.slice(0, 8)}-${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } finally {
      setExporting(false);
    }
  }

  return (
    <button
      onClick={handleExport}
      disabled={exporting}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        padding: '6px 14px',
        border: `1px solid ${hovered ? 'rgba(6,182,212,0.3)' : 'rgba(6,182,212,0.08)'}`,
        borderRadius: 2,
        background: hovered ? 'rgba(6,182,212,0.05)' : 'none',
        fontFamily: 'var(--font-jetbrains-mono)',
        fontSize: 10,
        letterSpacing: '0.1em',
        color: exporting ? 'var(--text-dim)' : (hovered ? '#06b6d4' : 'var(--text-secondary)'),
        cursor: exporting ? 'wait' : 'pointer',
        transition: 'all 0.2s',
        flexShrink: 0,
        display: 'flex',
        alignItems: 'center',
        gap: 6,
      }}
      aria-label="Export analysis as text report"
    >
      {exporting ? 'EXPORTING...' : 'EXPORT REPORT →'}
    </button>
  );
}
