/**
 * ClearChain — SAR Export Formatter
 *
 * Handles the last-mile formatting of AI-generated SAR draft text so that
 * compliance officers receive a consistently structured, traceable document.
 *
 * Two responsibilities:
 *   1. formatSARForDownload() — wraps the raw draft with a header block
 *      containing a case ID, timestamps, and a legal disclaimer, making it
 *      unambiguous that this is an AI-assisted draft pending officer review.
 *
 *   2. getSARFilename() — returns a deterministic, human-readable filename
 *      for the download, following the format used in the project spec.
 *
 * Case ID format: CLR-[YYYYMMDD]-[first 6 chars of address after 0x]
 * Example:        CLR-20260422-a1b2c3
 *
 * Filename format: clearchain-sar-[truncated address]-[YYYY-MM-DD].txt
 * Example:         clearchain-sar-0xa1b2c3...f4e5d6-2026-04-22.txt
 */

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Returns today's date as YYYYMMDD (UTC).
 * Using UTC ensures case IDs are consistent across server and client timezones.
 */
function todayCompact(): string {
  return new Date().toISOString().slice(0, 10).replace(/-/g, '');
}

/**
 * Returns today's date as YYYY-MM-DD (UTC) — used in the filename.
 */
function todayISO(): string {
  return new Date().toISOString().slice(0, 10);
}

/**
 * Extracts the 6-character suffix used in case IDs from an Ethereum address.
 * Strips the leading '0x' if present and lowercases for consistent formatting.
 */
function addressSuffix(address: string): string {
  const clean = address.startsWith('0x') ? address.slice(2) : address;
  return clean.slice(0, 6).toLowerCase();
}

/**
 * Produces a truncated display address for the filename, e.g.:
 * "0xa1b2c3...f4e5d6" — readable but not excessively long.
 */
function truncateAddress(address: string): string {
  if (address.length <= 12) return address;
  return `${address.slice(0, 8)}...${address.slice(-6)}`;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * formatSARForDownload
 *
 * Wraps the raw SAR draft text produced by generateSARDraft() with a
 * structured header block containing:
 *   - A generated case ID for internal tracking (CLR-[YYYYMMDD]-[addr6])
 *   - The wallet address being reported
 *   - The generation timestamp in ISO 8601 format
 *   - A clear legal disclaimer that this is a draft pending officer review
 *
 * The output is plain text formatted for human readability, suitable for
 * download as a .txt file or pasting into a compliance case management system.
 *
 * @param sarText  The raw SAR narrative text from generateSARDraft()
 * @param address  The Ethereum wallet address that was analysed
 * @returns        Formatted SAR document as a plain-text string
 */
export function formatSARForDownload(sarText: string, address: string): string {
  const caseId = `CLR-${todayCompact()}-${addressSuffix(address)}`;
  const generatedAt = new Date().toISOString();

  const header = [
    '================================================================',
    '  CLEARCHAIN — SUSPICIOUS ACTIVITY REPORT DRAFT',
    '  AI-Assisted | Pending Compliance Officer Review',
    '================================================================',
    `  Case ID        : ${caseId}`,
    `  Subject Wallet : ${address}`,
    `  Generated At   : ${generatedAt}`,
    `  Generated By   : ClearChain v1 (claude-sonnet-4-6)`,
    '----------------------------------------------------------------',
    '  DISCLAIMER: This document is an AI-generated draft produced',
    '  for internal compliance review purposes only. It does NOT',
    '  constitute a filed Suspicious Activity Report with FinCEN.',
    '  A qualified BSA/AML officer must review, verify, and approve',
    '  all information before any regulatory submission is made.',
    '================================================================',
    '',
  ].join('\n');

  const footer = [
    '',
    '================================================================',
    `  END OF DRAFT — Case ID: ${caseId}`,
    '  Verify all transaction data against source chain records',
    '  before filing. For questions, consult your BSA/AML officer.',
    '================================================================',
  ].join('\n');

  return `${header}${sarText}${footer}`;
}

/**
 * getSARFilename
 *
 * Returns a deterministic, human-readable filename for the SAR draft download.
 *
 * Format: clearchain-sar-[truncated_address]-[YYYY-MM-DD].txt
 * Example: clearchain-sar-0xa1b2c3...f4e5d6-2026-04-22.txt
 *
 * The truncated address ensures the filename remains filesystem-safe while
 * still being identifiable. The date stamp makes it easy to sort and archive.
 *
 * @param address  The Ethereum wallet address that was analysed
 * @returns        A safe, descriptive filename for the .txt download
 */
export function getSARFilename(address: string): string {
  const truncated = truncateAddress(address);
  const date = todayISO();
  // Replace any characters that could cause issues on Windows/macOS filesystems
  const safeAddress = truncated.replace(/[^a-zA-Z0-9._\-]/g, '_');
  return `clearchain-sar-${safeAddress}-${date}.txt`;
}

// ---------------------------------------------------------------------------
// Re-export for convenience — callers can import everything from lib/sar
// ---------------------------------------------------------------------------

/**
 * generateCaseId
 *
 * Utility export for cases where the case ID needs to be generated
 * independently of the full formatting step — e.g., for logging or
 * database record creation before the SAR text is available.
 *
 * @param address  The Ethereum wallet address that was analysed
 * @returns        Case ID string, e.g. "CLR-20260422-a1b2c3"
 */
export function generateCaseId(address: string): string {
  return `CLR-${todayCompact()}-${addressSuffix(address)}`;
}
